name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        # Aquí puedes añadir los comandos para ejecutar tus tests.

    - name: Build Docker Image
      run: |
        docker build . -t nombre_imagen

    - name: Push to Docker Registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag nombre_imagen:latest ${{ secrets.DOCKER_USERNAME }}/nombre_imagen:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nombre_imagen:latest

