version: '3.8'

services:
  web:
    build: .
    command: /bin/bash -c "python db.py && python aplicacion.py"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - .env

volumes:
  postgres_data:

